### ISSUE TITLE
Archives do not handle whole days well

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-manager-for-wp#10]
* [ ] This is because the end date does not need to be set when a whole day is selected. This could perhaps be solved by forcibly setting the end date to the end of that day when a whole day is chosen.
* [ ] When looking at a view that displays Current / upcoming events I should note that if an event started two days ago, but it ends today, I expect to see it in the current/upcoming views

**Comment by defries** [comment]
I need more context, perhaps an example, of what this really means.

**Comment by ryanhellyer** [comment]
The query which generates the content on the archive page (previous events page), looks for both the start and end times and spits out anything which occured in the past. This is breaking when the checkbox for an event which takes the whole day is selected, as that means the user doesn't need to bother with an end time.

Anything without both a start and end date currently does not show up on the archive (previous events) page.

**Comment by defries** [comment]
Right, so that needs to be handled better. Got it.

**Comment by defries** [comment]
When looking at a view that displays Current / upcoming events I should note that if an event started two days ago, but it ends today, I expect to see it in the current/upcoming views

**Comment by defries** [comment]
Are [both listed items](https://github.com/forsitemedia/events-manager-for-wp/issues/10#issue-159436239) fixed?

**Comment by ryanhellyer** [comment]
One is, another has had another ticket created specifically for it. I'll edit the original post to avoid confusion.
