### ISSUE TITLE
Allow for Multi-site mode

### ISSUE THREAD

**Issue by defries** [forsitemedia/events-manager-for-wp#3]
When this plugin is activated in network mode this multi-site module comes in action. It should provide for the following functionality:
* [x] Creating an event would be possible on any subsite. 
* [x] Events created on a subsite would display on that particular subsite, but also pulled in on the root site. 
* [x] Events which are created on subsites but displayed on the main site should use the [`rel="canonical"`](https://yoast.com/rel-canonical/) URL of the subsite.

**Comment by ryanhellyer** [comment]
> Events created on the root site should be able to be assigned to a subsite. Possibly by means of a custom taxonomy?

I'm evisaging this consisting of a meta box which appears only on the root site and allows the user to select a blog to have the post sent to on saving.

**Comment by ryanhellyer** [comment]
I think we should block users from editing events that are merely copies of an event on another site. Otherwise they're going to get grumpy if their changes are overridden.

**Comment by defries** [comment]
> I'm evisaging this consisting of a meta box which appears only on the root site and allows the user to select a blog to have the post sent to on saving.

Yes, that makes sense. That metabox has a dropdown with the subsites.

> I think we should block users from editing events that are merely copies of an event on another site. Otherwise they're going to get grumpy if their changes are overridden.

Smart thinking. If events are created on the root site than the subsite events are "locked" and if an event is created on a subsite, than the event on the root site is locked.

**Comment by ryanhellyer** [comment]
I've removed the task for replicating sites, and put it in this separate task (this one had too much unrelated text to read).

https://github.com/forsitemedia/events-manager-for-wp/issues/12
