### ISSUE TITLE
Convert event archive to page with shortcode

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-manager-for-wp#4]
As an option to the default installation, we should provide settings to make the URL structure a more flexible one. So, instead of using the WordPress post archive for the events post-type, it should use an automatically generated page with a shortcode to display the archive.

Resulting in something like this for example:
* [x] `domain.com/evenementen/`
* [x] `domain.com/evenementen/page/2/` (pagination)
* [x] `domain.com/evenementen/past-events/` (expired events)
* [x] `domain.com/evenement/some-event/` (single event)
* [x] `domain.com/event/` should redirect to `domain.com/events-archive/`
* [x] `domain.com/evenementen/archive/page/2` (pagination)
* [x] The `/past-events/` slugs should be controlled via a setting.
* [x] Settings page should reside as a subpage of the CPT menu.

**Comment by ryanhellyer** [comment]
^ I think that's a broken down very of everything discussed in chat, but if anything is missing, please edit accordingly :)

**Comment by ryanhellyer** [comment]
This does not require a shortcode to display the archive. The latest version includes options to show both upcoming or past event archives. The URLs are configurable via the new settings page.

Pagination is NOT working yet however.
Redirect from the root to the upcoming events is also not implemented yet.

**Comment by ryanhellyer** [comment]
I don't understand this one:
> * [ ] `domain.com/event/` should redirect to `domain.com/events-archive/`

What is "event" meant to represent here? (all of the other examples use `evenementen`.

**Comment by defries** [comment]
I'm sorry, that got a little mangled. The idea behind it was to have a landing page for the events that used a plural word such as:
`example.com/events/`
but to be able to to set single events to use a single event slug like:
`example.com/event/my-first-wordcamp/`

If and when those are both set, the `/event/`URL should redirect to the plural set landing page.

**Comment by ryanhellyer** [comment]
Pagination system is now working :)
