### ISSUE TITLE
Frontend output - single events

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-manager-for-wp#5]
The single events do not currently output the start and end dates. These should be added via the `the_content()` filter.

The layout should be based on this where possible:
https://autoevenementenagenda.nl/evenement/optocht-historische-en-moderne-brandweervoertuigen-de-bilt/

**Comment by defries** [comment]
Is @barrykooij's example added via the `the_content()` filter?

**Comment by defries** [comment]
The option to display previous and next events is indeed also [a good suggestion](https://github.com/forsitemedia/events-manager-for-wp/issues/6#issuecomment-224829469).

**Comment by ryanhellyer** [comment]
Yes, @barryjooij's example is added via the `the_content()` filter.

**Comment by ryanhellyer** [comment]
There are options on the example layout (on autoevenementenagenda.nl) for "More information" and "Event Type".

Should these two options be added to the plugin as well?

**Comment by defries** [comment]
Event Type would be a simple custom taxonomy, so yeah, that's probably a good idea.
More information would be powered by an URL input field in the event date metabox IMO.

**Comment by ryanhellyer** [comment]
This has been implemented. Finessing of the system, such as schema.org markup will be handled in other tickets.
