### ISSUE TITLE
Permalink Settings

### ISSUE THREAD

**Issue by defries** [forsitemedia/events-manager-for-wp#7]
We need settings for the following permalink options:
* [x] Base permalink `/event/` name of event vs. '/events/' or '/evenementen/`
* [x] Previous events slug
* [x] Upcoming events slug
* [x] Event Type taxonomy slug

**Comment by defries** [comment]
For the first one, mind you, I'm not talking about where the root of the events archive will be displayed via `[events-calendar]`, but more so what the base slug is for single events.

**Comment by ryanhellyer** [comment]
I will add a settings page for the plugin to allow for changing these values.

**Comment by defries** [comment]
As a submenu to the Custom Post Type menu, please.
