### ISSUE TITLE
Genesis Integration

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-manager-for-wp#8]
The default Genesis schema.org setting is blogpost. Set that to Event.

Also, override the Genesis content rather than using `the_content()` when Genesis is used. This avoids other plugins messing with the event posts output.

**Comment by ryanhellyer** [comment]
The schema.org markup actually was set with Event already.

**Comment by ryanhellyer** [comment]
What do you mean by "normal setting"?

**Comment by ryanhellyer** [comment]
I don't see any way to update it within an unknown theme.

**Comment by defries** [comment]
Not what I meant :) Basically what I mean is that the schema.org markup needs to validate in both the Genesis scenario as any ol' other theme.

**Comment by ryanhellyer** [comment]
Since we don't have any way to add schema.org markup to unknow themes, this shouldn't be a problem.
