### ISSUE TITLE
Schema.org markup

### ISSUE THREAD

**Issue by ryanhellyer** [forsitemedia/events-manager-for-wp#9]
Implement schema markup as used on https://autoevenementenagenda.nl/evenement/optocht-historische-en-moderne-brandweervoertuigen-de-bilt/

**Comment by defries** [comment]
It actually needs to be better than that because [I now see that the description includes other meta data as well](https://search.google.com/structured-data/testing-tool?hl=EN#url=https%3A%2F%2Fautoevenementenagenda.nl%2Fevenement%2Foptocht-historische-en-moderne-brandweervoertuigen-de-bilt%2F).

**Comment by defries** [comment]
If no external URL is set btw, the read more link, it should default to the permalink and not be visible in the output of the single event.

**Comment by defries** [comment]
Add a settings field that sets a default event image if one is not set as featured image.

**Comment by defries** [comment]
Schema should also work and validate on archives (cpt + custom taxonomy)

**Comment by ryanhellyer** [comment]
The intention here is to jam a DIV tag inside the_content(). This will cause problems for themes which already implement schema.org markup, but users of those themes can remove the filter we used to add the extra HTML.
